### ISSUE TITLE
Support : How can i apply this effect to a UITableViewCell

### ISSUE THREAD

**Issue by Jagadeeshwar-Reddy** [Ciechan/BCGenieEffect#1]
Hi, you have done a good job!

I am interested with this effect and i want to apply this effect as delete animation to my table view cell, on to a button which is on the out side view(super view)

can you suggest me to  achieve this

**Comment by Ciechan** [comment]
Well, I think it's possible, but you'll need to:
1. Modify code to insert `containerView` to tableView's superview and reposition it accordingly.
2. Call the genie effect on deleted UITableViewCell, in the completion block set the cell's transform to identity, cell's hidden to YES and delete row from tableView using any of the animations.
