### ISSUE TITLE
Problems with camera

### ISSUE THREAD

**Issue by k06a** [Ciechan/BCGenieEffect#10]
Try to record usage of Camera.app or any similar.

**Comment by Ciechan** [comment]
Are you sure this belongs here?

**Comment by k06a** [comment]
I am very sorry, I mean RecordMyScreen repository. Close this issue, please.

17.01.2013, в 1:04, Bartosz Ciechanowski notifications@github.com
написал(а):

Are you sure this belongs here?

—
Reply to this email directly or view it on
GitHubhttps://github.com/Ciechan/BCGenieEffect/issues/10#issuecomment-12339929.
