### ISSUE TITLE
SIGABRT inside bezierAxisIntersection on iPhone 4S (iOS 5.1.1)

### ISSUE THREAD

**Issue by k06a** [Ciechan/BCGenieEffect#11]
I have an SIGABRT on iPhone 4S (iOS 5.1.1)

```
2 libsystem_c.dylib 0x32dfc7ec _sigtramp + 48
3 libsystem_c.dylib 0x32df220e pthread_kill + 54
4 libsystem_c.dylib 0x32deb29e abort + 94
5 libsystem_c.dylib 0x32e0bcc0 asl_core_string_hash + 0
6 Pictography 0x00050b1e bezierAxisIntersection (UIView+Genie.m:485)
7 Pictography 0x00050668 -[UIView(Genie) transformationsForSlices:edge:startPosition:totalSize:firstBezier:secondBezier:finalRectDepth:] (UIView+Genie.m:353)
8 Pictography 0x0004f74e -[UIView(Genie) genieTransitionWithDuration:edge:destinationRect:reverse:completion:] (UIView+Genie.m:220)
9 Pictography 0x0004ee9e -[UIView(Genie) genieOutTransitionWithDuration:startRect:startEdge:completion:] (UIView+Genie.m:128)
```

I can't reproduce this problem.
This backtrace I just got from TestFlightApp.com
Why this can happen?

**Comment by Ciechan** [comment]
I have no idea. Those assertions are there to catch up situations that shouldn't possibly happen, but it seems that my logic must have been flawed at some point. I'll look into this in a spare time.

It's possible that letting this assertion go would do no harm at all. Moreover, assertion should not fire in release builds anyway - you can either delete them manually,or add NDEBUG flag for a release build.

**Comment by k06a** [comment]
There was only 3 crashes from 5000 runs...
