### ISSUE TITLE
I've just catched Assertion failed: (t >= 0 && t <= 1.0)

### ISSUE THREAD

**Issue by k06a** [Ciechan/BCGenieEffect#12]
I've played with animation and minimize and restore app many times.

```
Assertion failed: (t >= 0 && t <= 1.0), function bezierAxisIntersection, file /Users/k06a/Projects/Pictography/Pictography/UIView+Genie.m, line 509.
```

Here is my suppose (I don't saw your code detailed):
I think your method was called, then paused for long time, then resumed, checked real time and it is greater then 1.0

**Comment by Ciechan** [comment]
Could you provide more details? What is the start and the end frame? How long does the animation last? Are you calling the animation regular way or by `performSelector:withObject:afterDelay:`? Which iOS version is it?
