### ISSUE TITLE
iOS 5.0 requirement

### ISSUE THREAD

**Issue by odnoletkov** [Ciechan/BCGenieEffect#13]
I've been looking through the code and can't find a single ios5+ API used. It's kinda hard to test against iOS4 these days – is there any particular reason it won't work?

PS: thanks for the lib – animation looks really cool!

**Comment by Ciechan** [comment]
The only reason I put the iOS 5 requirement is that I just haven't tested it on iOS 4 so I didn't want to make any false promises. If you can somehow test it on iOS4 and it works then you should be OK :)
