### ISSUE TITLE
Major memory crashes when using this nice animation

### ISSUE THREAD

**Issue by harveyB** [Ciechan/BCGenieEffect#16]
Hi,

i was using your awesome animation, but was investigating a major memory crash in our app and found that the genieInTransition call is causing it because of unbounded memory growth that is not released. Everytime it is called, the memory is growing by 3MB and not reclaimed back. Now with Xcode 5, it is clearly shown in the execution pane and also when going to profiler from there.

Essentially, we are just creating a UIImageView and rendering the current screen to that using straightforward code from Apple:

-(UIImage *)snapshot()
{  
UIGraphicsBeginImageContext(self.view.bounds.size);
    [self.view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
return image;
 }

  UIImageView *ss = [[UIImageView alloc] initWithFrame:self.view.bounds];
    ss.image = [self snapshot];
      [ss genieInTransitionWithDuration:0.7 
    destinationRect:endRect 
               destinationEdge:BCRectEdgeTop 
                completion:^{

In XCode instruments, the allocations show huge nearly 3MB  growth  as below:

Event Type  ∆ RefCt   RefCt   Timestamp   Responsible Library Responsible Caller
0   VM Alloc    02:08.145.871   CoreGraphics    CGDataProviderCreateWithCopyOfData

The LiveBytes increases by 3MB everytime the genieInTransition is called. 
Graph    Category   Live Bytes  # Living    # Transient Overall Bytes   # Overall   Bytes Allocated (Net / Overall)
1   All Heap & Anonymous VM 12.16 MB    11263   3422178 597.30 MB   3433441 <XRRatioObject: 0x7fbca501d950>  %0.02, %0.98

It does not increase if the genie call is not made - so our app is crashing. We have the latest code with the previous memory fix in July or so.

I've looked at your code, but could not find any obvious leaks - but the code is complex - I'd appreciate your help - rendering the screen to an image is a core part of the functionality.

Thanks,
BH

**Comment by Ciechan** [comment]
Are you using the latest 1.1 version? There's been a leak inside the initial 1.0 release. What happens with `ss` UIImageView? Does it remain a subview or some view, or does anything else holds a strong reference to it? Could you provide me with a test project that recreates the issue?

**Comment by harveyB** [comment]
Hi, 

Re : version - yes, using the latest version - includes the     CGImageRelease(imageRef);

Re : UIImageView - it is added as a subview of the main view [to show the animation]. The memory problem happens even if it is removed right after using [ss removeFromSuperview]; . There is no strong ref to it as it is an automatic variable allocated on the stack. I am not even creating a block variable [which will create a copy] and removing it in the completion block...

thanks for the quick response - i'll send you a project or code shortly.

**Comment by harveyB** [comment]
hi,

big relief - here's what the problem was:

XCode gave an error on this line saying 
       [transforms[idx] addObject:obj];

../UIView+Genie.m:235:14: ARC Semantic issue: Multiple methods named 'addObject:' found with mismatched result, parameter type or attributes
Apparently, it could not resolve NSMutableArray addObject from two other matches:
- (NILinkedListLocation *)addObject:(id)object;
  @interface NIMutableTableViewModel : NITableViewModel
  - (NSArray *)addObject:(id)object;

So, what had happened was I had blindly added -fno-objc-arc to make this error go away resulting in huge memory leaks from calling genieInTransition

The correct solution was to cast it so XCode doesn't error out:
            [((NSMutableArray *)transforms[idx]) addObject:obj];

Now, there is no leak - what a relief!

Highly recommend that you do this cast [or something else to prevent XCode error] so others also dont blindly make this -fno-objc-arc - i think it classifies most errors as ARC issue which is misleading causing me [and possibly others] making such big mistakes.

One other thing I am wondering is why you didn't get this XCode error?

thanks for the cool animation.

**Comment by Ciechan** [comment]
I'm glad you found the root cause, these days it's quite easy to forget that disabling ARC doesn't magically insert `release`s ;).

I didn't got error since I don't have `NILinkedListLocation` class in my project (or any other class that has `addObject:` method for that matter).

I've updated the code with cast to remove the ambiguous call, thanks for finding the bug!

**Comment by harveyB** [comment]
sorry didn't check this sooner - it was not your bug - my mistake - appreciate your quick response - your animation is way cool...
