### ISSUE TITLE
Question: Is it safe to use on iOS5.0?

### ISSUE THREAD

**Issue by creatd** [Ciechan/BCGenieEffect#2]
Hi,

First of all thanks for this, it works great and I was able to apply within merely seconds. My question is, why is this control marked as iOS 5.1? I have it running on iOS 5.0 without any problem?

Thanks,
Ege

**Comment by Ciechan** [comment]
To be honest, the only reason it's marked as 5.1 is because I've used it on 5.1 device, and I didn't want to mark it as 5.0 without prior testing. As far as I'm aware I'm not calling any 5.1+ APIs and you if there aren't any problems then you should be safe using it on 5.0

**Comment by creatd** [comment]
That's what I'd thought. Thanks!
