### ISSUE TITLE
Great control! but how to make it works on ios4.3

### ISSUE THREAD

**Issue by garudaonekh** [Ciechan/BCGenieEffect#3]
hi,
Like it very much and very smooth. but i need it to support ios4.3 also.
Any suggestion is much appreciated.

Thanks;

**Comment by Ciechan** [comment]
Quite frankly I'm not really into doing API diffs on now obsolete versions of iOS, so I guess you're on your own with this one :). Have you tried running it on 4.3? Does it compile or are there any visual glitches?

**Comment by garudaonekh** [comment]
After removing Pan Gesture Recoginizer from the viewcontroller xib file, it worked like a charm on IOS 4.3

Thanks for your cool control!
